// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbuxdamawlpbtvqcocde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZidXhkYW1hd2xwYnR2cWNvY2RlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMDk0OTgsImV4cCI6MjA1OTg4NTQ5OH0.CqS1ldQWNtOwtl43KmT1w5fXdMq8lly-BCKTMwpbGFY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);